// User Roles
export enum UserRole {
  STUDENT = 'student',
  ADMIN = 'admin',
  SEATING_MANAGER = 'seating_manager',
  CLUB_COORDINATOR = 'club_coordinator',
}

// User Model
export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar?: string;
  // Student specific
  studentId?: string;
  batch?: string;
}

// Event/Calendar Model
export interface AcademicEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  type: 'exam' | 'club' | 'holiday' | 'academic';
  status: 'pending' | 'approved' | 'rejected';
  proposedBy?: string; // Club Coordinator ID
}

// Syllabus Model
export interface SyllabusTopic {
  title: string;
  subtopics: string[];
}

export interface Syllabus {
  id: string;
  subjectCode: string;
  subjectName: string;
  contentRaw: string; // Simulated PDF content text
  mindMapData?: SyllabusTopic[]; // Generated by AI
}

// Seating Model
export interface ExamRoom {
  id: string;
  name: string;
  rows: number;
  cols: number;
  capacity: number;
}

export interface StudentSeat {
  studentId: string;
  studentName: string;
  examSubject: string;
  seatNumber: string; // e.g., A1, B2
}

export interface Allocation {
  roomId: string;
  examId: string;
  seats: StudentSeat[];
}

// Exam Model
export interface Exam {
  id: string;
  name: string;
  date: string;
  time: string;
  subjects: string[];
}
